### ISSUE TITLE
Database query spans are off and can surpass endpoint time

### ISSUE THREAD

**Issue by amcsi** [nipwaayoni/elastic-apm-laravel#15]
I would expect queries to not overlap with each other (since queries are not asynchronous in PHP generally), and also that their spans would stay within the span of the API request.

Here are some screenshots from Kibana:

![2020-06-22_11-39](https://user-images.githubusercontent.com/116494/85272941-2a313100-b47d-11ea-8012-d118415fc3b1.png)

![2020-06-22_11-42](https://user-images.githubusercontent.com/116494/85273134-7e3c1580-b47d-11ea-8c73-a4a669acfb44.png)

**Comment by dstepe** [comment]
The current method for logging queries is to listen for `QueryExecuted` events. Those events only carry the duration of the query, not the start time. The start time is derived by subtracting the duration from the current timestamp. That works if the events are dispatched to the listener immediately. I suspect that the Laravel event system used to work that way and therefore this provided a mostly accurate representation of the spans.

However, not it appears the Laravel event system collects events during the request and dispatches them all at once, most likely after the response has been sent. This makes sense in terms of optimizing the response time. I have not done the research to confirm this theory, but I seem to recall DB queries being correctly rendered at some point and I can't think of another explanation.

I'm not sure what options we'll have to remedy this since it seems to be a shortcoming in the Laravel DB events. I'll keep digging into it.

**Comment by dstepe** [comment]
I believe this is fixed in the 7.0.1 release being prepped. Are you able to try out that branch before I merge it?

I was completely wrong on the underlying cause. I forgot that changes in the Agent package required that Span creation be redone in this package. I had only done enough to prove it worked and had neglected to actually handle the start time of the query.

**Comment by amcsi** [comment]
@dstepe see what I wrote here: #16

**Comment by amcsi** [comment]
Looks great now. Thanks!
Closing.
